receivers:
  otlp:
    protocols:
      http:
      grpc:

exporters:
  debug: {}   

  otlphttp:
    endpoint: http://tempo:4318

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlphttp]